package trading.strategy

/**
 * Trading signal generated by strategy evaluation
 * 
 * WHY: Immutable signal object prevents accidental modification and ensures
 * clear separation between signal generation and execution
 */
sealed class TradeSignal {
    object None : TradeSignal() {
        override fun toString() = "NONE"
    }
    
    data class Long(
        val confidence: Double,        // 0.0 to 1.0
        val entryPrice: Double,        // Suggested entry price
        val stopLoss: Double?,         // Optional stop loss
        val takeProfit: Double?        // Optional take profit
    ) : TradeSignal() {
        override fun toString() = "LONG(confidence=$confidence, entry=$entryPrice)"
    }
    
    data class Short(
        val confidence: Double,        // 0.0 to 1.0
        val entryPrice: Double,        // Suggested entry price
        val stopLoss: Double?,         // Optional stop loss
        val takeProfit: Double?        // Optional take profit
    ) : TradeSignal() {
        override fun toString() = "SHORT(confidence=$confidence, entry=$entryPrice)"
    }
    
    /**
     * Returns true if signal is actionable (not None)
     */
    fun isActionable(): Boolean = this !is None
    
    /**
     * Returns true if signal is a LONG
     */
    fun isLong(): Boolean = this is Long
    
    /**
     * Returns true if signal is a SHORT
     */
    fun isShort(): Boolean = this is Short
    
    /**
     * Gets the suggested entry price, or null if None
     */
    fun getEntryPrice(): Double? = when (this) {
        is Long -> entryPrice
        is Short -> entryPrice
        is None -> null
    }
}

